IronLanguages/dlr

Src/Microsoft.Dynamic/Math/BigIntegerV2.cs

Range PR in ironpython3 depends on it.

added MinusOne to match System.Numerics

---

.editorconfig
.gitattributes

in case core.autocrlf is not set

added .gitattributes

---

.gitignore
Build/AssemblyVersion.targets
Build/Common.proj

This allows the submodule build to work correctly

Change build variables for submodule usage

---

Src/Microsoft.Dynamic/Debugging/DebugFrame.cs
Src/Microsoft.Dynamic/Debugging/DebugSourceSpan.cs
Src/Microsoft.Dynamic/Debugging/DebugThread.cs
Src/Microsoft.Dynamic/Debugging/DefaultRuntimeVariablesImpl/DebugRuntimeVariables.cs
Src/Microsoft.Dynamic/Debugging/FunctionInfo.cs
Src/Microsoft.Dynamic/Debugging/VariableInfo.cs
Src/Microsoft.Dynamic/Runtime/CustomStringDictionary.cs
Src/Microsoft.Dynamic/Utils/ExceptionUtils.cs
Src/Microsoft.Dynamic/Utils/MathUtils.cs
Src/Microsoft.Scripting/Runtime/LanguageBoundTextContentProvider.cs

Covers: IronLanguages/main#1294, IronLanguages/main#1363, part of IronLanguages/main#1466 and part of IronLanguages/main#1477

Changes from ipy2.7

---

Build/net45.props
Src/Microsoft.Dynamic/Interpreter/InterpretedFrame.cs

Workaround for IronLanguages/ironpython2#27

Workaround for IronLanguages/ironpython2#27

---

.gitignore
.travis.yml
Dlr.sln
NuGet.config
Src/Microsoft.Dynamic/Utils/MathUtils.cs
Tests/Microsoft.Dynamic.Test/Microsoft.Dynamic.Test.csproj
Tests/Microsoft.Dynamic.Test/Utils/MathUtilsTest.cs
appveyor.yml

I suspect I need to check the appveyor/travis files to run these?

Add some MathUtils tests

---

appveyor.yml

Readd the nuget restore to appveyor.yml to see if it helps with CI issues.

Readd nuget restore to appveyor.yml

---

Build/net40.props
Build/net45.props
Src/Microsoft.Dynamic/Generation/CompilerHelpers.cs

Remove FEATURE_ARGITERATOR

---

Tests/ClrAssembly/ClrAssembly.csproj

Test now compiled with ilasm from Mono

Re-add test

---

.gitignore
.travis.yml
Makefile
Tests/ClrAssembly/ClrAssembly.csproj

Some fixes for .NET Core on Linux

Fixes for mono updates

---

Src/Microsoft.Dynamic/Interpreter/InterpretedFrame.cs
Tests/Microsoft.Dynamic.Test/InterpreterTest.cs

See https://github.com/IronLanguages/ironpython2/issues/273

Clear intepreter stack after pop

---

Src/Microsoft.Dynamic/Interpreter/Instructions/DynamicInstructions.Generated.cs
Src/Microsoft.Dynamic/Interpreter/LightCompiler.cs
Src/Microsoft.Dynamic/Runtime/IdDispenser.cs
Src/Microsoft.Dynamic/Utils/ReflectionUtils.cs
Src/Microsoft.Dynamic/Utils/WeakDictionary.cs
Src/Microsoft.Scripting/LanguageOptions.cs
Src/Microsoft.Scripting/PlatformAdaptationLayer.cs

Resolves https://github.com/IronLanguages/dlr/issues/85

Make IsCompactFramework obsolete

---

Build.proj
Src/Microsoft.Dynamic/Microsoft.Dynamic.csproj
Src/Microsoft.Scripting.Metadata/Microsoft.Scripting.Metadata.csproj
Src/Microsoft.Scripting/Microsoft.Scripting.csproj
Tests/ClrAssembly/ClrAssembly.csproj
Tests/Metadata/Metadata.csproj
Tests/Microsoft.Dynamic.Test/Microsoft.Dynamic.Test.csproj
Tests/Microsoft.Scripting.Test/Microsoft.Scripting.Test.csproj

Project file cleanup

---

Dlr.sln
Tests/ClrAssembly/ClrAssembly.csproj

- ClrAssembly improvements:
- Incremental targets.
- Better support for the dotnet cli.
- Clean deletes all generated assemblies.
- Fixed Dlr.sln broken paths.

ClrAssembly improvements

---

Src/Microsoft.Dynamic/Utils/MathUtils.cs

Prep work for https://github.com/IronLanguages/ironpython2/issues/373

Add GetRandBits overload

---

Src/Microsoft.Dynamic/zlib.net/ZStream.cs
Src/Microsoft.Scripting.Metadata/MemoryBlock.cs
Src/Microsoft.Scripting.Metadata/MetadataServices.cs
Src/Microsoft.Scripting.Metadata/MetadataTables.CCI.cs
Src/Microsoft.Scripting/IndexSpan.cs
Src/Microsoft.Scripting/Microsoft.Scripting.csproj
Src/Microsoft.Scripting/Runtime/ContextId.cs
Src/Microsoft.Scripting/SourceLocation.cs
Src/Microsoft.Scripting/SourceSpan.cs
Src/Microsoft.Scripting/Utils/AssemblyQualifiedTypeName.cs
Src/Microsoft.Scripting/Utils/CollectionExtensions.cs

Specifically adds C# 7.2 `readonly` to some structs. Also adds `IEquatable<T>` to some structs, use auto properties and other code cleanups.

Use C# 7.2 features

---

CurrentVersion.props
Src/Microsoft.Dynamic/Generation/AssemblyGen.cs
Src/Microsoft.Dynamic/Runtime/SavableScriptCode.cs

This will be used by some updates I am doing in ipyc.

Updates to DLR for DLL generation

---

Tests/Microsoft.Dynamic.Test/InterpreterTest.cs

Bypass GC test on Mono

---

Src/Microsoft.Dynamic/Utils/ReflectionUtils.cs

Related to https://github.com/IronLanguages/ironpython2/issues/546

Copy default value in CopyMethodSignature

---

Src/Microsoft.Dynamic/Interpreter/Instructions/LessThanInstruction.cs

While technically a breaking change all(?) the other instructions are internal so this brings things in line with them.

Change LessThanInstruction to internal

---

Src/Microsoft.Dynamic/Actions/NamespaceTracker.cs

Broke in https://github.com/IronLanguages/dlr/pull/158

Fix assertion error

---

Src/Microsoft.Dynamic/ComInterop/ComBinder.cs
Src/Microsoft.Dynamic/ComInterop/ComMetaObject.cs

Fixes some Reflection that broke with https://github.com/IronLanguages/dlr/pull/199

Fix issue with COM cleanup

---

Src/Microsoft.Dynamic/Utils/MathUtils.cs
Tests/Microsoft.Dynamic.Test/Utils/MathUtilsTest.cs

Made RoundAwayFromZero obsolete.
Added new general purpose Round method that takes a mode parameter.

Round of an integer should return an integer 505

---

Src/Microsoft.Dynamic/Generation/CompilerHelpers.cs

Resolves https://github.com/IronLanguages/dlr/issues/233

Check for PNSE when calling DebugInfoGenerator.CreatePdbGenerator

---

Src/Microsoft.Dynamic/Actions/Calls/DefaultOverloadResolver.cs

This facilitates IronLanguages/ironpython3#999. Should have gone with #241.

Support Extensible<string> in splatting

---

Src/Microsoft.Dynamic/Actions/Calls/OverloadInfo.cs
Src/Microsoft.Scripting/Hosting/ScriptSource.cs
Src/Microsoft.Scripting/SourceUnit.cs

Resolves IronLanguages/ironpython3#1681

Eliminate use of coalescing operator in DebuggerDisplayAttribute

---

Src/Microsoft.Scripting/Runtime/ScopeStorage.cs

Fast path when item is found in ScopedStorage, skips redundant FindEntry call

Skip double FindEntry in ScopedStorage.TryGetValue
