IronLanguages/dlr

appveyor.yml

Initial attempt builds and runs the TestInternalDLR.exe. No ```nunit``` style results are written, so no publication of results to the ```Tests``` tab. But, better to have some CI than none at all.

Add appveyor.yml for continuous integration

---

Build/net45.props
Build/netcoreapp2.0.props
Src/Microsoft.Dynamic/Actions/DefaultBinder.Operations.cs
Src/Microsoft.Dynamic/Actions/MemberTracker.cs
Src/Microsoft.Dynamic/Actions/NamespaceTracker.cs
Src/Microsoft.Dynamic/Ast/ConstantExpression.cs
Src/Microsoft.Dynamic/Generation/CompilerHelpers.cs
Src/Microsoft.Dynamic/Generation/Snippets.cs
Src/Microsoft.Dynamic/Runtime/AssemblyTypeNames.cs
Src/Microsoft.Dynamic/Runtime/ExtensionTypeAttribute.cs
Src/Microsoft.Dynamic/Utils/AssemblyQualifiedTypeName.cs
Src/Microsoft.Dynamic/Utils/ReflectionUtils.cs
Src/Microsoft.Scripting/Hosting/ScriptRuntime.cs
Src/Microsoft.Scripting/Hosting/ScriptRuntimeSetup.cs
Src/Microsoft.Scripting/Runtime/DlrConfiguration.cs
Src/Microsoft.Scripting/Runtime/DynamicOperations.cs
Src/Microsoft.Scripting/Runtime/LanguageContext.cs
Src/Microsoft.Scripting/Stubs.cs
Src/Microsoft.Scripting/Utils/AssemblyQualifiedTypeName.cs

This gets rid of `TypeInfo` related stuff.
The only reason to keep `TypeInfo` would be to support .NET Core 1.0 or Win 8/10. To target Windows UWP we would have to restrict ourselves to the Fall Creators Update (October 2017) or later which supports .NET Standard 2.0 (and so `TypeInfo` would no longer be required). Since we haven't officially supported any of those in the past I see no reason to keep the code...

Remove usage of TypeInfo

---

Tests/ClrAssembly/ClrAssembly.csproj

Mono now packages the VB.NET compiler from Roslyn, so re-enable the builds.

Re-add VB.NET Builds

---

Src/Microsoft.Dynamic/ComInterop/VarEnumSelector.cs
Src/Microsoft.Dynamic/Generation/ILGen.cs
Src/Microsoft.Dynamic/Interpreter/Instructions/AddInstruction.cs
Src/Microsoft.Dynamic/Interpreter/LightCompiler.cs

I replaced the existing class code with the corresponding .NET Core code minus the following:
- They use different variable names, s_Int16 instead of _Int16 for example.
- They use extension methods such as GetNonNullableType and IsArithmetic. Maybe we want to change them in separate PR for all files?
Also, the order of some methods is different. Do we want to keep our order?
Finally, they use InstructionName instead of overriding ToString. Do we want that change?

Convert AddInstruction classes closer to .NET Core implementation

---

Src/Microsoft.Dynamic/Ast/LightExceptionRewriter.cs
Src/Microsoft.Dynamic/Interpreter/Instructions/Instruction.cs
Src/Microsoft.Dynamic/Interpreter/Instructions/InstructionList.cs
Src/Microsoft.Dynamic/Interpreter/Instructions/TypeOperations.cs

The changes in `InstructionList` resolve a minor issue with IronPython3 where `assert id(True) == id(True is True)` would fail. The other changes are just cleanup.

Change EmitLoad(bool) to use boxed true/false values

---

DLR.ruleset
Src/Microsoft.Dynamic/Microsoft.Dynamic.csproj
Src/Microsoft.Scripting.Metadata/Microsoft.Scripting.Metadata.csproj
Src/Microsoft.Scripting/Microsoft.Scripting.csproj

@slide perhaps you could setup a [Dependabot](https://dependabot.com/) (or something similar) account, so that when DLR is updated, it automatically creates a PR to update the submodule in IronPython 2 and 3 repositories?

Update FxCopAnalyzers to version 2.6.3

---

Build/netstandard2.0.props
Dlr.sln
Package/nuget/DynamicLanguageRuntime.nuspec
Src/Microsoft.Dynamic/Debugging/DelegateHelpers.cs
Src/Microsoft.Dynamic/Generation/AssemblyGen.cs
Src/Microsoft.Dynamic/Generation/CompilerHelpers.cs
Src/Microsoft.Dynamic/Generation/DynamicILGen.cs
Src/Microsoft.Dynamic/Generation/FieldBuilderExpression.cs
Src/Microsoft.Dynamic/Generation/ILGen.cs
Src/Microsoft.Dynamic/Generation/Snippets.cs
Src/Microsoft.Dynamic/Generation/ToDiskRewriter.cs
Src/Microsoft.Dynamic/Generation/TypeGen.cs
Src/Microsoft.Dynamic/Microsoft.Dynamic.csproj
Src/Microsoft.Dynamic/Utils/ReflectionUtils.cs
Src/Microsoft.Scripting.Metadata/Microsoft.Scripting.Metadata.csproj
Src/Microsoft.Scripting/Microsoft.Scripting.csproj
Src/Microsoft.Scripting/Utils/DelegateUtils.cs
Src/Microsoft.Scripting/Utils/NativeMethods.cs
Tests/Microsoft.Dynamic.Test/TestReflectionServices.cs
make.ps1

I have tested deploying this as a Nuget Package, referencing and using the nuget package from a .Net Standard class library, and then calling the library from both .Net Core and .Net Framework. Everything works as expected.
I hope that once this is merged, supporting .Net Standard for IronPython should be trivial.

Support .Net Standard

---

make.ps1

Mirrors IronLanguages/ironpython3#564.

Make make.ps1 executable in a portable way

---

Src/Microsoft.Dynamic/Utils/MathUtils.cs
Src/Microsoft.Dynamic/Utils/StringUtils.cs

With .NET Core 3, `Double.TryParse` no longer throws for values that are too large. Replace method to check for infinity and throw.

Fix double parsing for .NET Core 3

---

Src/Microsoft.Dynamic/Hosting/Shell/SuperConsole.cs

When pasting text in the Windows Terminal, both CR and LF are pasted and `OnEnter` is called twice. This changes the behavior so that only CR is counted as an Enter.

Fix SuperConsole handling of LF

---

Src/Microsoft.Dynamic/Utils/StringUtils.cs

These simply forward to existing .NET methods so no point in keeping them.

Mark some methods as Obsolete

---

Src/Microsoft.Dynamic/MutableTuple.cs
Tests/Metadata/Metadata.csproj
Tests/Microsoft.Dynamic.Test/Microsoft.Dynamic.Test.csproj
Tests/Microsoft.Dynamic.Test/TestTuple.cs
Tests/Microsoft.Scripting.Test/Microsoft.Scripting.Test.csproj

Specifying the size helps avoid running into the size issue explained in https://github.com/IronLanguages/dlr/issues/231

Expose MutableTuple.GetAccessPath with size

---

Src/Microsoft.Dynamic/Actions/DefaultBinder.MethodCalls.cs

This facilitates IronLanguages/ironpython3#999.
It think ideally a given key should be coerced only when `[ParamDictionary]` is applied on a parameter of a generic type with `string` as `TKey`, while maintaining its identity for `object` cases. But this would require much ore extensive changes and so far I haven't see a need for it in IronPython. But the least the DLR can do is to **accept** `Extensible<string>` as the key type.
This coercing could also have been done at the IronPython level, but I believe it is more elegant in the DLR, and, frankly, where it belongs, sine `Extensible<>` is defined here too.

Coerce Extensible<string> to string if used as ParamDictionary key

---

Src/Microsoft.Dynamic/Actions/Calls/ParamsDictArgBuilder.cs
Src/Microsoft.Dynamic/Runtime/BinderOps.cs
Src/Microsoft.Dynamic/Utils/CollectionExtensions.cs
Src/Microsoft.Scripting/Runtime/ParamDictionaryAttribute.cs

This, when completed, will facilitate IronLanguages/ironpython3#882.
I implemented support only for `IReadOnlyDictionary<string, anything>` and not for `IReadOnlyDictionary<object, anything>` like for other generic types supported, because I fail to see any benefit of supporting dictionary interfaces that take `object` type as key, and sticking to `string` eliminates one cast for every runtime call for every kwarg param. The whole param dictionary machinery in DLR assumes that keyword parameter names are strings. If the client code really needs `<object, anything>` specialization to e.g. pass it on somehere down the road, it can always simply declare `Dictionary<object, something>`.

Support ParamDictionaryAttribute on IReadOnlyDictionary

---

Src/Microsoft.Dynamic/Actions/Calls/ActualArguments.cs
Src/Microsoft.Dynamic/Actions/Calls/BindingTarget.cs
Src/Microsoft.Dynamic/Actions/Calls/CallFailure.cs
Src/Microsoft.Dynamic/Actions/Calls/CandidateSet.cs
Src/Microsoft.Dynamic/Actions/Calls/MethodCandidate.cs
Src/Microsoft.Dynamic/Actions/Calls/OverloadResolver.cs
Src/Microsoft.Dynamic/Actions/Calls/ParamsDictArgBuilder.cs
Src/Microsoft.Dynamic/Runtime/BinderOps.cs
Tests/ClrAssembly/Src/methodargs.cs

There are a number of issues with the DLR overload resolver, which I am looking into now, but the code is so wonderfully complex that I prefer to start with something simple, to build confidence. Here is such change: it is not functional (it doesn't change how the resolving happens), it merely makes the error messages more specific in case of duplicate arguments.
Currently, for duplicate arguments, the message is "_MethodName_() got multiple values for keyword argument '_arg_'". To me it suggests that a keyword argument _arg_ is duplicated, but it can also be reported when an argument is provided by position and keyword, which is also a clash.
To be more accurate, positional/keyword clash is not handled well at all, sometimes resulting in strange messages as "_MethodName_() takes at least …

Explicit message for keyword/positional argument conflict

---

Src/Microsoft.Dynamic/Actions/Calls/DefaultOverloadResolver.cs
Src/Microsoft.Dynamic/Actions/Calls/OverloadResolver.cs
Src/Microsoft.Dynamic/Actions/Calls/ParameterMapping.cs
Src/Microsoft.Dynamic/Actions/Calls/ParamsDictArgBuilder.cs
Src/Microsoft.Dynamic/Utils/ReflectionUtils.cs
Src/Microsoft.Scripting/Runtime/ParamDictionaryAttribute.cs
Tests/ClrAssembly/Src/methodargs.cs

This fixes
```Python
import clr
clr.AddReference("rowantest.methodargs")
from Merlin.Testing.Call import VariousParameters
obj = VariousParameters()
obj.M560(1, 2, 3, z=4, b=5, c=6)
```
reported in #249.
Disabling by-keyword assignment to param arrays and dictionaries is controlled though a virtual method on `OverloadResolver`, but I stopped short from making it protected since the DLR currently cannot handle the "enabled" case so I did not want the languages to start requesting it. It can go in three ways from here:
1. The DLR implements `PositonalOnlyAttribute`/`NonKeywordAttribute` for the benefit of all languages. Probably the best way to support it is in `ReflectionUtils` and the virtual extension point maybe can be abolished (i.e. preventing binding by keyword to param …

Prevent ParamArray and ParamDictionary parameters from binding by keyword

---

Src/Microsoft.Dynamic/Hosting/Shell/SuperConsole.cs

The main motivation for this PR was terrible command-line editing experience on macOS. The existing keybindings for moving the cursor on the input line are _Home_/_End_ and _Ctrl-Left_/_Ctrl-Right_ (move to the beginning/end of line, begining of previous/next word respectively) are by default used by the macOS Terminal app (scrolling the output buffer, switching to other window instances). This leaves only the _Left_/_Right_ cursor keys for editing, which is quite inconvenient on longer lines.
Many programs (bash, zsh, pwsh, python) on Linux and macOS adapt the GNU Readline convention, which is a subset of Emacs keybindings. Python's StdLib has even module `readline` to write interactive programs that support commandline editing using the GNU Readline keybindings. This PR adds support for …

Add GNU Readline keybindings in SuperConsole

---

Src/Microsoft.Scripting/Runtime/SharedIO.cs
Src/Microsoft.Scripting/Utils/ConsoleInputStream.cs

When trying to use IronPython3 from a Blazor web-assembly application, `Microsoft.Scripting.Runtime.SharedIO` throws an exception when trying to setup `stdin`, which is understandable, because there is none.
All I did is catch the exception and set the stream to `Stream.Null`.

BlazorWasm support

---

Build.proj
Build/net6.0.props
Dlr.sln
Package/nuget/DynamicLanguageRuntime.nuspec
Src/Microsoft.Dynamic/Actions/EventTracker.cs
Src/Microsoft.Dynamic/ComInterop/ComEventSink.netcoreapp.cs
Src/Microsoft.Dynamic/ComInterop/ComEventSinksContainer.cs
Src/Microsoft.Dynamic/ComInterop/ComObject.cs
Src/Microsoft.Dynamic/ComInterop/ComRuntimeHelpers.cs
Src/Microsoft.Dynamic/ComInterop/ComTypeClassDesc.cs
Src/Microsoft.Dynamic/ComInterop/ComTypeEnumDesc.cs
Src/Microsoft.Dynamic/ComInterop/DispatchArgBuilder.cs
Src/Microsoft.Dynamic/ComInterop/IDispatchComObject.cs
Src/Microsoft.Dynamic/ComInterop/Variant.cs
Src/Microsoft.Dynamic/Hosting/Shell/BasicConsole.cs
Src/Microsoft.Dynamic/Hosting/Shell/CommandLine.cs
Src/Microsoft.Dynamic/Hosting/Shell/ConsoleHost.cs
Src/Microsoft.Dynamic/Interpreter/Interpreter.cs
Src/Microsoft.Dynamic/Microsoft.Dynamic.csproj
Src/Microsoft.Scripting.Metadata/Microsoft.Scripting.Metadata.csproj
Src/Microsoft.Scripting/Microsoft.Scripting.csproj
Tests/Metadata/Metadata.csproj
Tests/Microsoft.Dynamic.Test/Microsoft.Dynamic.Test.csproj
Tests/Microsoft.Scripting.Test/Microsoft.Scripting.Test.csproj

Disabled CA1416 in COM related code and SYSLIB0006.

Add net6.0 to package

---

Src/Microsoft.Scripting/Utils/TextStream.cs

`TextStream` was removed as part of Silverlight cleanup (#25) but is still required to build the DLR if `FEATURE_FULL_CONSOLE` is disabled but `FEATURE_BASIC_CONSOLE` enabled.
Besides, it is useful to run IronPython 3 in LinqPad.

Resurrect TextStream

---

Src/Microsoft.Dynamic/Utils/WeakDictionary.cs

Something I have noticed while working on IronLanguages/IronPython3#1711. I submit it for the sake of correctness; it seems I will not be using `HybridMapping` in `PythonFileManager` after all.

Improve thread safety of HybridMappimg

---

Src/Microsoft.Dynamic/Hosting/Shell/BasicConsole.cs
Src/Microsoft.Dynamic/Hosting/Shell/ConsoleHost.cs
Src/Microsoft.Dynamic/Hosting/Shell/ConsoleOptions.cs
Src/Microsoft.Dynamic/Hosting/Shell/OptionsParser.cs
Src/Microsoft.Dynamic/Hosting/Shell/SuperConsole.cs

Option `-X ColorfulConsole` was not working, for several reasons:
1. The fag mask used to set colors was incorrect, resulting all colors be coerced to either white or black.
2. The fallback color was white, which for white background always resulted in the text being invisible (macOS default console has white background).
3. The background detection was working only on Windows, on Unix, the background color is unknown. So to make this option usable on Unix systems, I extended it with an optional parameter of value _dark_ or _light_. To prevent proliferation of constructor parameters and the number of constructors of `BasicConsole` and `SuperConsole`, they both got a constructor that accepts `ConsoleOptions` and picks up the option it can understand.

Fix option ColorfulConsole

---

Src/Microsoft.Scripting/Runtime/SharedIO.cs

I plan to use this test to protect standard file descriptors from accidental closure, when closing a Python file object (`FileIO`) using those descriptors. See also IronLanguages/ironpython3#1711.

Add detection of standard IO streams

---

Build/net452.props
Build/net6.0.props
Build/netcoreapp3.1.props
Build/netstandard2.0.props
Src/Microsoft.Dynamic/Hosting/Shell/BasicConsole.cs
Src/Microsoft.Dynamic/Hosting/Shell/CommandLine.cs
Src/Microsoft.Dynamic/Hosting/Shell/ConsoleHost.cs
Src/Microsoft.Dynamic/Hosting/Shell/ConsoleHostOptions.cs
Src/Microsoft.Dynamic/Hosting/Shell/ConsoleHostOptionsParser.cs
Src/Microsoft.Dynamic/Hosting/Shell/ConsoleOptions.cs
Src/Microsoft.Dynamic/Hosting/Shell/IConsole.cs
Src/Microsoft.Dynamic/Hosting/Shell/OptionsParser.cs
Src/Microsoft.Dynamic/Hosting/Shell/Remote/ConsoleRestartManager.cs
Src/Microsoft.Dynamic/Hosting/Shell/Remote/RemoteCommandDispatcher.cs
Src/Microsoft.Dynamic/Hosting/Shell/Remote/RemoteConsoleCommandLine.cs
Src/Microsoft.Dynamic/Hosting/Shell/Remote/RemoteConsoleHost.cs
Src/Microsoft.Dynamic/Hosting/Shell/Remote/RemoteRuntimeServer.cs
Src/Microsoft.Dynamic/Hosting/Shell/SuperConsole.cs
Src/Microsoft.Dynamic/PerfTrack.cs
Src/Microsoft.Scripting/Runtime/SharedIO.cs
Src/Microsoft.Scripting/Utils/ConsoleInputStream.cs
Src/Microsoft.Scripting/Utils/TextStream.cs

The level of console support is selectable at build time through compile symbols `FEATURE_FULL_CONSOLE` and `FEATURE_BASIC_CONSOLE`.
1. When `FEATURE_FULL_CONSOLE` is defined, standard IO is performed using .NET console streams. This option is preferable for a standalone `ipy` program.
2. When `FEATURE_BASIC_CONSOLE` is defined, standard IO is performed using console reader/writer. This option may be preferable in some embedded cases when the hosting source code is not available and performs its own redirection (like _LinqPad_).
3. When neither is defined, standard IO is silently discarded.
4. When both are defined at the same time, the current code defaults to using .NET console streams.
The last case is interesting because this is the build feature set that is available on NuGet. The …

Make BASIC and FULL console support runtime-selectable if both available

---

Src/Microsoft.Dynamic/DebugOptions.cs
Src/Microsoft.Dynamic/Generation/AssemblyGen.cs

Resolves some warnings-turned-errors.

Avoid ToLoverInvariant in string comparisons (CA1862)

---

.github/workflows/main.yml
Directory.Build.props
Src/Microsoft.Dynamic/Debugging/DebugInfoRewriter.cs

This should resolve the issue from https://github.com/IronLanguages/ironpython3/pull/1810 where the first trace event is not getting generated.

Fix for missing trace event on first expression

---

.github/workflows/main.yml
Build.proj
Build/steps.yml
Package/nuget/DynamicLanguageRuntime.nuspec
Tests/Metadata/Metadata.csproj
Tests/Microsoft.Dynamic.Test/Microsoft.Dynamic.Test.csproj
Tests/Microsoft.Scripting.Test/Microsoft.Scripting.Test.csproj
make.ps1

Drop .NET Core 3.1 testing and also removes .NET 6 from packaging.

Drop .NET Core 3.1 testing
